name: Update README
on:
  schedule:
    - cron: "0 */1 * * *"  # Every 1 hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2505359
          sessionCookie: ${{ secrets.AOC_SESSION }}
          starSymbol: 🌟
      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
          commit_message: Update README stars
